### ISSUE TITLE
Bower/NPM

### ISSUE THREAD

**Issue by designbyadrian** [yuichiroharai/easeplus-velocity#1]
Hello

> 'easeplus-velocity' is not in the npm registry.

I humbly request for your plugin to be added to Bower as well!

**Comment by yuichiroharai** [comment]
Sorry, I don't have any plans to publish to npm/Bower at this point in time.
(I've been busy day in and day out...)

Alternatively, we could use blow.

```
npm install https://github.com/yuichiroharai/easeplus-velocity.git

bower install https://github.com/yuichiroharai/easeplus-velocity.git
```

Thanks.
